name: Вопрос или предложение
description: Есть идея или нужна помощь — пишите!
labels: [question]
body:
  - type: input
    id: contact
    attributes:
      label: Контакт
      description: Как с вами связаться (email, Telegram)
      placeholder: опционально
  - type: textarea
    id: text
    attributes:
      label: Ваш вопрос или предложение
      description: Опишите подробно
      placeholder: Что хотите предложить или спросить?
    validations:
      required: true
